Create Table Manipal(Name varchar(50) Primary key, Distance int(3), Tags varchar(500));

insert into Manipal values("The Hanging Bridge", 13, "Nature, Kayaking");
insert into Manipal values("Agumbe", 45, "Nature, Trekking, Sightseeing, Sunset");
insert into Manipal values("Karkala", 35, "Nature, Pilgrimage, Temples, Jain, Manasthamhha, Dock, Ramasamudra lake");
insert into Manipal values("Mudbidri", 55, "Nature, Mudbidri Temple");
insert into Manipal values("Dharmasthala", 92, "Nature, Car Museum, Gomateshwara, Ram Mandir");
insert into Manipal values("Kundapura", 41, "Nature, Kodi Seawalk, Marwante Beach, Beach, Kodi Lighthouse");
insert into Manipal values("Chikmangalur", 90, "Nature, Peaks, Ranijhari Peak, Muliyangiri Peak, trekking, Neelakurunji");
insert into Manipal values("Malpe Beach", 11, "Nature, Beach, Beach games, Parachute Riding");
insert into Manipal values("Kollur", 78, "Nature, Mookambika Temple, Wildlife Sanctuary, Garuda Guhe, Arsingundi Falls, Kodachadri Nature Camp");
insert into Manipal values("Kudremukh", 98, "Nature, Trekking, Hanging Bridge, Waterfalls");
insert into Manipal values("Delta point", 15, "Nature, River, Sea, beach, peace");
insert into Manipal values("Murdeshwar beach" , 89, "Beach, view");
insert into Manipal values("Murdeshwar Temple", 88 , "Temple, View, Lord Shiva Idol");
insert into Manipal values("Udupi Krishna temple",  3.5, "Temple, peace, worship, Lord Krishna Idol");
insert into Manipal values("Kapu Beach", 15 , "Beach, Light house");
insert into Manipal values("Coorg" , 127 , "Water falls, Jeep ride, safari, nature, plantation");
insert into Manipal values("End point", 2, "View, Nature, sunrise");
insert into Manipal values("Pilikula", 50, "Botanical garden, zoo, science Center, planetarium,lake");
insert into Manipal values("Manipal lake" , 2, "nature, lake");
insert into Manipal values("Arbi Falls", 2, "Water falls, view");
insert into Manipal values("Kaup Beach", 21, "Nature, Beach, Lighthouse");
insert into Manipal values("Jogigundi Falls", 52, "Nature, Waterfall, Trekking, Rainforest");
insert into Manipal values("Barkur", 21, "Historical, Pilgrimage");
insert into Manipal values("Sringeri", 76, "Nature, Pilgrimage, Heritage, Waterfall, Hill Station, Beach, Trekking");
insert into Manipal values("Gomatheshwara Statue", 37, "Historical, Pilgrimage, Karkala");
insert into Manipal values("Hastha Shilpa Antique Museum", 3, "Museum, Historical, Art, Craft");
insert into Manipal values("St. Lawrence Church", 34, "Pilgrimage, Historical, Attur, Karkala");
insert into Manipal values("Kere Basadi", 33, "Pilgrimage, Nature, Varanga, Lake, Monument");
insert into Manipal values("Baindur", 74, "Historical, Pilgrimage, Beach, Swimming, Water Sports, Resort");
insert into Manipal values("Narasimha Parvatha Trek", 55, "Adventure , Trekking, Nature, Peaks, Camp, Waterfall, Forest, Agumbe");